---
apiVersion: v1
kind: Namespace
metadata:
  name: parus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parus-config
  labels:
    app: parus-web
data:
  ORACLE_SID: "ORCLPDB1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parus-web
  labels:
    app: parus-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parus-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: parus-web
    spec:
      containers:
        - name: parus-web
          image: cr.nexus.local/parusweb2:8.561.31
          envFrom:
            - configMapRef:
                name: parus-config
#            - secretRef:
#                name: parus-credentials
          ports:
            - containerPort: 5121
              name: parus-embwebproxy
---
apiVersion: v1
kind: Service
metadata:
  name: embwebproxy
  labels:
    app: parus-web
spec:
  ports:
    - name: embwebproxy
      port: 5121
      targetPort: parus-embwebproxy
  selector:
    app: parus-web