pipeline { 
  agent {
    kubernetes {
      cloud 'local'
      inheritFrom 'podman'
    }
  }
  stages {
      stage('Parus Web Extra Build') {
       steps {
         container ('podman') {
           script {
             sh "cd dockerfiles/web2"
             sh "curl -k https://nexus.local:31111/repository/parus/service/8.561-0823/extra.zip"
             sh "podman build --tls-verify=false ."
           }
         }
       }
      }
//      stage("Quality Gate") {
//            steps {
//            }
//      }
  }
}