pipeline { 
  agent {
    kubernetes {
      cloud 'local'
      inheritFrom 'podman'
    }
  }
  stages {
      stage('Parus Web Extra Build') {
       steps {
         container ('podman') {
           script {
             sh "curl -k -o dockerfiles/web2/extra.zip https://nexus.local:31111/repository/parus/service/8.561-0823/extra.zip"
             withEnv([EDITION = ${env.BUILD_NUMBER}]) {
               sh "podman build --tls-verify=false dockerfiles/web2/."
             }
           }
         }
       }
      }
//      stage("Quality Gate") {
//            steps {
//            }
//      }
  }
}